file=open("Myfile.txt","w")
file.write("Hello charansai\n")
file.write("Welcome to Python Programming Lab\n")
file.writelines(["Line 1:Example\n","Line 2:Program\n","Line 3:For files\n"])
file.close()
print("Data Written into the File Successfully\n")
file=open("Myfile.txt","r")
print("Using Read():")
print(file.read())
file.close()
print("Data red into the File Successfully\n")
file=open("Myfile.txt","r")
print("Using Readline():")
print(file.readline())
print(file.readline())
file.close()
file=open("Myfile.txt","r")
print("Using readlines()")
print(file.readlines())
file.close()
