file = open("sample2.txt", "w+")
file.write("Hello Charan ")
file.write("Example for Files in Python ")
file.flush()
print("Current position after write:", file.tell())
file.seek(0)
print("Content before seek(12):")
print(file.read())
file.seek(12)
print("After seek(), position:", file.tell())
content = file.read()
print("Content:", content)
file.close()
